# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('IssueDate', models.DateField(auto_now=True, verbose_name='\u53d1\u884c\u65f6\u95f4')),
                ('modtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'movie theater',
                'verbose_name': '\u7535\u5f71',
            },
        ),
    ]
